name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  POSTGRES_DB: slicer
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Start PostgreSQL on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "DO \$\$
          BEGIN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'postgres') THEN
              CREATE USER postgres WITH PASSWORD 'postgres' SUPERUSER;
            ELSE
              ALTER USER postgres WITH PASSWORD 'postgres' SUPERUSER;
            END IF;
          END
          \$\$;"
          sudo -u postgres psql -c "SELECT 'CREATE DATABASE slicer' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'slicer')\gexec"

      - name: Start PostgreSQL on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew services start postgresql@14
          sleep 5
          createuser -s postgres
          createdb slicer

      - name: Install PostgreSQL client (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql-client

      - name: Install PostgreSQL client (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install libpq postgresql@14
          brew link --force libpq

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/slicer
